    // 获取响应体
    let body = $response.body;
    let obj = JSON.parse(body); // 将响应体解析为JSON对象

    // 提取 mxxh 并找到最大值
    let mxxhList = obj.data.nsmxList.map(item => parseInt(item.mxxh));  // 将 mxxh 转换为整数
    let maxMxxh = Math.min(...mxxhList);  // 使用 Math.max 获取最大值

    console.log("最大 mxxh 值是: " + maxMxxh);
    
    if (maxMxxh < 33960385340) {
     console.log("2023数据"); 
     obj.data = {
                "ybtseHj" : 11089.8,
                "sreHj" : 211900,
                "nsmxList" : [
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJIdDKTOMJeS04XKGmW/hoZYfynJSBHM0TiYIbjn/r8JX",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1701360000000,
                    "sblsh" : "2000003362034517",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "33179444498",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1703952000000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1698768000000,
                    "sblsh" : "2000003300064745",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "32504334477",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1701273600000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1696089600000,
                    "sblsh" : "2000003248552044",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "31924778139",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1698681600000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1693497600000,
                    "sblsh" : "2000003194930633",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "31391373003",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1696003200000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1690819200000,
                    "sblsh" : "2000003136460770",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "30744215822",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1693411200000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1688140800000,
                    "sblsh" : "2000003089138111",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "30146160124",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1690732800000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1685548800000,
                    "sblsh" : "2000003028366062",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "29497771957",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1688054400000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1682870400000,
                    "sblsh" : "2000002957339975",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "28672021404",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 1093.4,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1685462400000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "全年一次性奖金收入",
                    "skssqq" : 1682870400000,
                    "sblsh" : "2000002957339975",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "28672021405",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 489,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1685462400000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0103"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1680278400000,
                    "sblsh" : "2000002860111048",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "27824416468",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 869.6,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1682784000000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1677600000000,
                    "sblsh" : "2000002762557223",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "27118567022",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 328,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1680192000000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1675180800000,
                    "sblsh" : "2000002589308750",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "26267779649",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 328,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1677513600000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  },
                  {
                    "nsrdah" : "fUZNWINaFl2qizSEVpuFJGmK4LlI+YwRzI+0/ahtmoj74NF9FMQvyTYeBK9PqP3/",
                    "kjywrMc" : "深圳正中云有限公司",
                    "sre" : 16300,
                    "grsdssdxmmc" : "正常工资薪金",
                    "skssqq" : 1672502400000,
                    "sblsh" : "2000002533624327",
                    "jyqdMc" : "其他",
                    "btzqynsrsbh" : null,
                    "mxxh" : "25661201927",
                    "ywlxDm" : "A061005019",
                    "sdxmDlmc" : "工资薪金",
                    "ybtse" : 328,
                    "kjywrlbDm" : "1",
                    "sdxmDlDm" : "0100",
                    "skssqz" : 1675094400000,
                    "btzdwmc" : null,
                    "zybz" : null,
                    "grsdssdxmDm" : "0101"
                  }
                ],
                "rowCount" : 13
     }
    }else{
     console.log("2024数据"); 
     obj.data = {
                    "ybtseHj" : 9996.4,
                    "sreHj" : 195600,
                    "nsmxList" : [
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1730390400000,
                        "sblsh" : "2000004276066420",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "41281357167",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1732896000000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1727712000000,
                        "sblsh" : "2000004215641834",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "40590816350",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1730304000000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1725120000000,
                        "sblsh" : "2000004154697139",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "39972656465",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1727625600000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1722441600000,
                        "sblsh" : "2000004099426451",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "39281664092",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1725033600000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1719763200000,
                        "sblsh" : "2000004039004628",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "38609554394",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1722355200000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1717171200000,
                        "sblsh" : "2000003965568965",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "37877319444",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1719676800000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "全年一次性奖金收入",
                        "skssqq" : 1714492800000,
                        "sblsh" : "2000003891205223",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "37049799263",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 489,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1717084800000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1714492800000,
                        "sblsh" : "2000003891205223",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "37049799262",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 1093.4,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1717084800000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1711900800000,
                        "sblsh" : "2000003798456022",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "36279873965",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 869.6,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1714406400000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1709222400000,
                        "sblsh" : "2000003677990559",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "35438948103",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 328,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1711814400000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1706716800000,
                        "sblsh" : "2000003490658891",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "34531706292",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 328,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1709136000000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      },
                      {
                        "nsrdah" : "fUZNWINaFl2qizSEVpuFJEGYzYAo4Dqbwv0eqevcHgBAaTtuv/0raSOFbWQ1PWH7",
                        "kjywrMc" : "深圳正中云有限公司",
                        "sre" : 16300,
                        "grsdssdxmmc" : "正常工资薪金",
                        "skssqq" : 1704038400000,
                        "sblsh" : "2000003440346628",
                        "jyqdMc" : "其他",
                        "btzqynsrsbh" : null,
                        "mxxh" : "33960385340",
                        "ywlxDm" : "A061005019",
                        "sdxmDlmc" : "工资薪金",
                        "ybtse" : 328,
                        "kjywrlbDm" : "1",
                        "sdxmDlDm" : "0100",
                        "skssqz" : 1706630400000,
                        "btzdwmc" : null,
                        "zybz" : null,
                        "grsdssdxmDm" : "0101"
                      }
                    ],
                    "rowCount" : 12
                };
    };
    

    // 将修改后的对象转换回JSON字符串
    body = JSON.stringify(obj);

    // 替换响应体
    $done({body});


